version: "3.3"

services:
  api:
    build: .
    container_name: "${CONT_NAME}"
    ports:
      - "${API_PORT}:80"

  db:
    image: mongo:4.4.6
    container_name: "${DB_CONT_NAME}"
    ports:
      - "${DB_PORT}:27017"
    restart: always
